### PR TITLE
[Fix] Multiclassing Max Spell Points

### PR DESCRIPTION
**Pull request by kyleady**
When using `_calculateSpellPointsFixed()` to calculate the maximum spell points of a character that has multiclassed into multiple spellcasting classes, an incorrect calculation is made.

The SRD has rules for Multiclassing with caster classes [here](https://5thsrd.org/rules/multiclassing/#class-features). FoundryVTT's 5e system uses the multiclassing rules for calculating spell slots. See how [their code](https://gitlab.com/foundrynet/dnd5e/-/blob/master/module/actor/entity.js#L527-553) calculates Spell Slots.

Example:
Previously when a character had two levels of Bard and two levels of Cleric, it calculated their spell points based on the slots they would have individually, thus calculating spell points as if the character had three + three = six first level slots and zero second level slots.

Now when a character has two levels of Bard and two levels of Cleric, their spell casting levels are added together and the number of slots are determined by the Spell Casting multiclassing chart. giving four 1st level slots and three 2nd level slots.

### CODE REVIEW

**Comment by misthero** [comment]
does this still aplly on latest versione @kyleady  ?

**Comment by kyleady** [comment]
Yes, this fix is still needed for all FoundryVTT versions.

The bug is only affecting the DMG fixed formula, which is the default option for all new users.

**Comment by misthero** [comment]
I'm really sorry @kyleady I forgot this in the latest version, now it is conflicting, can you make a new pull request for the new version?

**Comment by kyleady** [comment]
Resolved @misthero

**Pull request merged**
